server:
  port: 8082

dubbo:
  application:
    name: apache-dubbo-consumer
  registry:
    #    address: redis://172.16.2.141:6379
    address: zookeeper://172.16.2.141:2181?backup=172.16.2.96:2181,172.16.2.97:2181,172.16.2.214:2181
    group: dubbo
demo:
  service:
    version: 1.0.0
